--- #YAML:1.0
name: CGI-Session-Driver-pure_sql
version: 0.61
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Pure SQL driver with no embedded Perl stored in the database
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  CGI::Session: 4.13
  Date::Calc: 0
  SQL::Abstract: 0
provides:
  CGI::Session::Driver::pure_sql:
    file: lib/CGI/Session/Driver/pure_sql.pm
    version: 0.61
  CGI::Session::Serialize::sql_abstract:
    file: lib/CGI/Session/Serialize/sql_abstract.pm
    version: 0.61
generated_by: Module::Build version 0.2807
meta-spec:
  url: |-
    http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
